services:
  redis:
    image: redis
    volumes:
      - ./data:/data
    networks:
      - store-network
  counter:
    build: ./books-counter
    ports:
      - 3001:3002
    environment:
      # - PORT=3001
      - REDIS_URL=redis://redis
    depends_on:
      - redis
    networks:
      - store-network
  store:
    build: ./books-store
    ports:
      - 3000:3000
    depends_on:
      - counter
    networks:
      - store-network
    volumes:
      - ./books-store/public:/app/public
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=db
    networks:
      - store-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - store-network
networks:
  store-network:
